In [1]:
import torch 
import math

In [3]:
x=torch.empty(3, 4) #allocates_memory_for_tensor_but_does_not_initialize_it_with_any_value
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
ones=torch.ones(2, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.manual_seed(1729)
random=torch.rand(3,5)
random

tensor([[0.3126, 0.3791, 0.3087, 0.0736, 0.4216],
        [0.0691, 0.2332, 0.4047, 0.2162, 0.9927],
        [0.4128, 0.5938, 0.6128, 0.1519, 0.0453]])

In [11]:
x=torch.empty(2, 2, 3)
x.shape
x

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [12]:
empty_like_x=torch.empty_like(x)
print(empty_like_x)
print(empty_like_x.shape)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])


In [13]:
zeros_like_x=torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [14]:
ones_like_x=torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [15]:
rand_like_x=torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0.5035, 0.9978, 0.3884],
         [0.6929, 0.1703, 0.1384]],

        [[0.4759, 0.7481, 0.0361],
         [0.5062, 0.8469, 0.2588]]])


In [16]:
a=torch.ones((2, 3), dtype=torch.int16)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [17]:
b=torch.rand((2, 3), dtype=torch.float64)*20
b

tensor([[ 3.3046,  9.4177,  1.6821],
        [17.7372, 13.2388, 15.9839]], dtype=torch.float64)

In [18]:
c=b.to(torch.int32)
c

tensor([[ 3,  9,  1],
        [17, 13, 15]], dtype=torch.int32)

In [19]:
#Arithmetic_with_scalers
ones=torch.zeros(2, 2)+1
twos=torch.ones(2, 2)*2
threes=(torch.ones(2, 2)*7-1)/2
fours=twos**2
sqrts=twos**0.5

In [20]:
print(ones)
print(twos)
print(threes)
print(fours)
print(sqrts)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [21]:
#similar_operations_between_two_tensor
powers2=twos**torch.tensor([[1, 2], [3, 4]])
print(powers2)

tensor([[ 2.,  4.],
        [ 8., 16.]])


In [22]:
fives=ones+fours
print(fives)

tensor([[5., 5.],
        [5., 5.]])


In [23]:
dozens=threes*fours
print(dozens)

tensor([[12., 12.],
        [12., 12.]])


In [25]:
#Tensor_broadcasting
rand=torch.rand(2, 4)
doubled=rand*(torch.ones(1, 4)*2)
print(rand)
print(doubled)

tensor([[0.4067, 0.7301, 0.6276, 0.7357],
        [0.0381, 0.2138, 0.5395, 0.3686]])
tensor([[0.8134, 1.4602, 1.2551, 1.4715],
        [0.0762, 0.4276, 1.0791, 0.7371]])


In [27]:
a=torch.ones(4, 3, 2)
b=a*torch.rand( 3, 2)
print(b)

tensor([[[0.4007, 0.7220],
         [0.8217, 0.2612],
         [0.7375, 0.8328]],

        [[0.4007, 0.7220],
         [0.8217, 0.2612],
         [0.7375, 0.8328]],

        [[0.4007, 0.7220],
         [0.8217, 0.2612],
         [0.7375, 0.8328]],

        [[0.4007, 0.7220],
         [0.8217, 0.2612],
         [0.7375, 0.8328]]])


In [28]:
c=torch.rand( 3, 1)
print(c)

tensor([[0.8444],
        [0.2941],
        [0.3788]])


In [29]:
d=a*torch.rand( 1, 2)
print(d)

tensor([[[0.4567, 0.0649],
         [0.4567, 0.0649],
         [0.4567, 0.0649]],

        [[0.4567, 0.0649],
         [0.4567, 0.0649],
         [0.4567, 0.0649]],

        [[0.4567, 0.0649],
         [0.4567, 0.0649],
         [0.4567, 0.0649]],

        [[0.4567, 0.0649],
         [0.4567, 0.0649],
         [0.4567, 0.0649]]])


In [32]:
a=torch.ones(4, 3, 2)
b=a*torch.rand(  3, 2 )
print(a)
print(b)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([[[0.6324, 0.9464],
         [0.0113, 0.5183],
         [0.9807, 0.6545]],

        [[0.6324, 0.9464],
         [0.0113, 0.5183],
         [0.9807, 0.6545]],

        [[0.6324, 0.9464],
         [0.0113, 0.5183],
         [0.9807, 0.6545]],

        [[0.6324, 0.9464],
         [0.0113, 0.5183],
         [0.9807, 0.6545]]])


In [34]:
c=a*torch.rand(  3,2)
print(c)

tensor([[[0.4922, 0.5461],
         [0.5396, 0.3053],
         [0.1973, 0.3285]],

        [[0.4922, 0.5461],
         [0.5396, 0.3053],
         [0.1973, 0.3285]],

        [[0.4922, 0.5461],
         [0.5396, 0.3053],
         [0.1973, 0.3285]],

        [[0.4922, 0.5461],
         [0.5396, 0.3053],
         [0.1973, 0.3285]]])


In [39]:
#common_functions
a=torch.rand(2, 4)*2-1
print('Common Function:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

Common Function:
tensor([[0.2155, 0.5310, 0.4235, 0.4804],
        [0.1066, 0.6997, 0.7201, 0.8560]])
tensor([[1., -0., 1., 1.],
        [-0., 1., -0., 1.]])
tensor([[ 0., -1.,  0.,  0.],
        [-1.,  0., -1.,  0.]])
tensor([[ 0.2155, -0.5000,  0.4235,  0.4804],
        [-0.1066,  0.5000, -0.5000,  0.5000]])


In [40]:
#trigonometric_functions_and_their_inverses
angles=torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
sines=torch.sin(angles)
inverses=torch.asin(sines)
print('nsine and arcsine:')
print(angles)
print(sines)
print(inverses)

nsine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [41]:
#bitwise_operations
print('\nBitwise XOR:')
b=torch.tensor([1, 5, 11])
c=torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))


Bitwise XOR:
tensor([3, 2, 1])


In [42]:
#comparisons:-
print('\nBroadcasted, element wise equality comparisons:')
d=torch.tensor([[1., 2.],[3., 4.]])
e=torch.ones(1, 2)
print(torch.eq(d, e)) #return_a_tensor_of_bool_type


Broadcasted, element wise equality comparisons:
tensor([[ True, False],
        [False, False]])


In [48]:
#reductions:-
print('\nReduction ops:')
print(torch.max(d))
print(torch.max(d).item()) #extract_value_from_tensor
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) #filter_unique_elements


Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [51]:
#vector_and_linear_algebra_operations
v1=torch.tensor([1., 0., 0.])#x_unit_vector
v2=torch.tensor([0., 1., 0.])#y_unit_vector
m1=torch.rand(2, 2)
m2=torch.tensor([[3., 0.],[0., 3.]]) #3-times_identity_matrix
print('\nvectors and Matrics:')
print(v1)
print(m1)
print(torch.cross(v2, v1)) #-ve_of_z_unit_vector=-v2Xv1
m3=torch.matmul(m1, m2) #matrix_multiplication
print(m3)
print(torch.svd(m3))


vectors and Matrics:
tensor([1., 0., 0.])
tensor([[0.1631, 0.7391],
        [0.9254, 0.2546]])
tensor([ 0.,  0., -1.])
tensor([[0.4894, 2.2173],
        [2.7763, 0.7638]])
torch.return_types.svd(
U=tensor([[-0.5211, -0.8535],
        [-0.8535,  0.5211]]),
S=tensor([3.1867, 1.8144]),
V=tensor([[-0.8236,  0.5672],
        [-0.5672, -0.8236]]))


/var/folders/cj/0w5hsz6d7hsgpdmwp3dwlw2w0000gn/T/ipykernel_26749/2631559135.py:9: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/Cross.cpp:67.)
  print(torch.cross(v2, v1)) #-ve_of_z_unit_vector=-v2Xv1


In [53]:
a=torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
print('a:')
print(a)
print(torch.sin(a)) #creates_a_new_tensor_in_memory
print(a)

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])


In [54]:
b=torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
print('\nb:')
print(b)
print(torch.sin_(b)) #this_changes_b
print(b)


b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [56]:
#for_arithmetic_operations_there_are_functions_that_behave_similarly
a=torch.ones(2, 2)
b=torch.rand(2, 2)
print('before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nafter Multiplying:')
print(b.mul_(b))
print(b)

before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.7992, 0.0554],
        [0.5776, 0.9130]])

After adding:
tensor([[1.7992, 1.0554],
        [1.5776, 1.9130]])
tensor([[1.7992, 1.0554],
        [1.5776, 1.9130]])
tensor([[0.7992, 0.0554],
        [0.5776, 0.9130]])

after Multiplying:
tensor([[0.6388, 0.0031],
        [0.3336, 0.8335]])
tensor([[0.6388, 0.0031],
        [0.3336, 0.8335]])


In [57]:
if torch.cuda.is_available():
    print('We have a GPU')
else:
    print('Sorry We have CPU only!')

Sorry We have CPU only!


In [58]:
#get_data_on_targeted_device
if torch.cuda.is_available():
    gpu_rand=torch.rand(2, 2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry!, CPU only')
    

Sorry!, CPU only


In [60]:
if torch.cuda.is_available():
    my_device=torch.device('cuda')
else:
    my_device=torch.device('cpu')
print('Device:{}'.format(my_device))
x=torch.rand(2, 2, device=my_device)
print(x)

Device:cpu
tensor([[0.2881, 0.2677],
        [0.3067, 0.6961]])


In [61]:
#move_tensor_from_one_device_to_another
y=torch.rand(2, 2)
y=y.to(my_device)

In [62]:
y

tensor([[0.5406, 0.5028],
        [0.0389, 0.1795]])