In [1]:
import torch

In [3]:
#Aurograd_package_provides_autmatic_differentiation
x=torch.randn(3, requires_grad=True)
x

tensor([-0.6169,  0.5451, -0.1838], requires_grad=True)

In [4]:
y=x+2
y#gradient_Function_attribute_as_it_is_created_by_applying_function_on_x

tensor([1.3831, 2.5451, 1.8162], grad_fn=<AddBackward0>)

In [5]:
print(y.grad_fn)#grad_fun:references_a_function_that_created_tensor

In [6]:
z=y*y*3
z

tensor([ 5.7386, 19.4327,  9.8959], grad_fn=<MulBackward0>)

In [8]:
z=z.mean()
z

tensor(11.6891, grad_fn=<MeanBackward0>)

In [9]:
z.backward()

In [10]:
print(x.grad)#dz/dx

tensor([2.7661, 5.0902, 3.6324])


In [12]:
#Stop_a_tensor_from_tracking_history
a=torch.randn(2,2)
a

tensor([[ 0.1555,  1.2289],
        [-0.3314, -0.4207]])

In [13]:
print(a.requires_grad)

False


In [14]:
b=((a*3)/(a-1))
print(b.grad_fn)

None


In [15]:
a.requires_grad_(True)

tensor([[ 0.1555,  1.2289],
        [-0.3314, -0.4207]], requires_grad=True)

In [16]:
print(a.requires_grad)

True


In [17]:
b=(a*a).sum()

In [18]:
print(b.grad_fn)

In [20]:
#detach():-get_a_new_tensor_with_same_content_but_no_gradient_computation
a=torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)

True


In [21]:
b=a.detach()
print(b.requires_grad)

False


In [22]:
a=torch.randn(2, 2 , requires_grad=True)
print(a.requires_grad)

True


In [23]:
with torch.no_grad():
    print((x**2).requires_grad)

False


In [26]:
#Emptying_Gradients-need_to.zero()_the_gradients_before_updating_the_weights_and_before_going_to_next_iteration
weights=torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)
    with torch.no_grad():
        weights-= 0.1*weights.grad
    weights.grad.zero_()
print(weights)
print(model_output)

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)


In [29]:
#Backpropagation_for_linear_Regression
x= torch.tensor(1.0)
y= torch.tensor(2.0)

w= torch.tensor(1.0, requires_grad=True)

#forward_pass_to_computer_loss
y_predicted= w*x
loss= (y_predicted-y)**2
print(loss)

#backward_pass_to_compute_gradient
loss.backward()
print(w.grad)

with torch.no_grad():
    w-= 0.01*w.grad
w.grad.zero_()

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


tensor(0.)

In [31]:
#Gradient_Descent_for_linear_Regression
import numpy as np
X=np.array([1, 2, 3, 4], dtype=np.float32)
Y=np.array([2, 4, 6, 8], dtype=np.float32)
w=0.0
def forward(x):
    return w*x
def loss(y, y_pred):
    return ((y_pred-y)**2).mean()
def gradient(x, y, y_pred):
    return np.mean(2*x*(y_pred-y))
print(f'Prediction Before Training:f(5)={forward(5):.3f}')

#Training
learning_rate=0.01
n_iters=100
for epoch in range(n_iters):
    y_pred=forward(X)
    l=loss(Y, y_pred)
    dw=gradient(X, Y, y_pred)
    w=w-learning_rate*dw
    if epoch%10==0:
        print(f'epoch {epoch+1}:w={w:.3f}, loss={l:.8f}')
print(f'Prediction after Training:f(5)={forward(5):.3f}')

Prediction Before Training:f(5)=0.000
epoch 1:w=0.300, loss=30.00000000
epoch 11:w=1.665, loss=1.16278565
epoch 21:w=1.934, loss=0.04506905
epoch 31:w=1.987, loss=0.00174685
epoch 41:w=1.997, loss=0.00006770
epoch 51:w=1.999, loss=0.00000262
epoch 61:w=2.000, loss=0.00000010
epoch 71:w=2.000, loss=0.00000000
epoch 81:w=2.000, loss=0.00000000
epoch 91:w=2.000, loss=0.00000000
Prediction after Training:f(5)=10.000


In [33]:
#Gradient_Descent_Automatic
X=torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y=torch.tensor([2, 4, 6, 8], dtype=torch.float32)
w=torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
def forward(x):
    return w*x
def loss(y, y_pred):
    return ((y_pred-y)**2).mean()
print(f'Prediction before training:f(5)={forward(5).item():.3f}')

learning_rate=0.01
n_iters=100
for epoch in range(n_iters):
    y_pred=forward(X)
    l=loss(Y, y_pred)
    l.backward()
    dw=w.grad
    
    with torch.no_grad():
        w-=learning_rate*dw
        
    w.grad.zero_()
    if epoch%10==0:
        print(f'epoch {epoch+1}: w={w.item():.3f}, loss={l.item():.8f}')
print(f'Prediction after training: f(5)={forward(5).item():.3f}')

    


Prediction before training:f(5)=0.000
epoch 1: w=0.300, loss=30.00000000
epoch 11: w=1.665, loss=1.16278565
epoch 21: w=1.934, loss=0.04506890
epoch 31: w=1.987, loss=0.00174685
epoch 41: w=1.997, loss=0.00006770
epoch 51: w=1.999, loss=0.00000262
epoch 61: w=2.000, loss=0.00000010
epoch 71: w=2.000, loss=0.00000000
epoch 81: w=2.000, loss=0.00000000
epoch 91: w=2.000, loss=0.00000000
Prediction after training: f(5)=10.000
